version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.1
    - 7.0.4
    - 8.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.12
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: write-good
    versions:
    - 1.0.7
